# Generated by Django 5.2.11 on 2026-09-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classcontent",
            name="class_type",
            field=models.CharField(
                choices=[
                    ("YOUTUBE", "YouTube Video/Stream"),
                    ("ZOOM", "Zoom Meeting/Class"),
                    ("GOOGLE_MEET", "Google Meet"),
                ],
                db_index=True,
                default="ZOOM",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="classcontent",
            name="external_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Direct link for YouTube, Zoom, or Google Meet class",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="classcontent",
            name="video_file",
            field=models.FileField(
                blank=True, editable=False, null=True, upload_to="classes/videos/%Y/%m/"
            ),
        ),
    ]
