# Generated by Django 5.2.11 on 2026-09-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0002_alter_classcontent_class_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="end_time",
            field=models.TimeField(
                blank=True, help_text="Batch class end time", null=True
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="start_time",
            field=models.TimeField(
                blank=True, help_text="Batch class start time", null=True
            ),
        ),
    ]
