# Generated by Django 5.2.11 on 2026-09-29 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0003_batch_end_time_batch_start_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
            },
        ),
    ]
