# Generated by Django 5.2.11 on 2026-09-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0004_alter_report_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[
                    ("PUBLISHED", "Published"),
                    ("PENDING", "Pending Moderation"),
                    ("FLAGGED", "Flagged"),
                    ("HIDDEN", "Hidden"),
                    ("REMOVED", "Removed by Admin"),
                ],
                db_index=True,
                default="PUBLISHED",
                max_length=20,
            ),
        ),
    ]
