# Generated by Django 5.2.11 on 2026-09-29 11:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0005_alter_review_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformAnnouncement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, default="", max_length=50)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "announcement_type",
                    models.CharField(
                        choices=[
                            ("IMPORTANT", "Important"),
                            ("PROMOTIONAL", "Promotional"),
                            ("GENERAL", "General"),
                        ],
                        db_index=True,
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("ALL_USERS", "All Users"),
                            ("STUDENTS", "Students"),
                            ("TEACHERS", "Teachers"),
                        ],
                        db_index=True,
                        default="ALL_USERS",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PUBLISHED", "Published"),
                            ("SCHEDULED", "Scheduled"),
                            ("DRAFT", "Draft"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="announcements/%Y/%m/"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_announcements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Announcement",
                "verbose_name_plural": "Platform Announcements",
                "ordering": ["-created_at"],
            },
        ),
    ]
