# Generated by Django 5.2.11 on 2026-09-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0006_platformannouncement"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformannouncement",
            name="clicks_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="platformannouncement",
            name="cta_label",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="platformannouncement",
            name="cta_url",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="platformannouncement",
            name="impressions_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="platformannouncement",
            name="is_banner",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="platformannouncement",
            name="slot",
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
