# Generated by Django 5.2.11 on 2026-09-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0007_platformannouncement_clicks_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studymaterial",
            name="chapters_count",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="studymaterial",
            name="code",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="studymaterial",
            name="downloads_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studymaterial",
            name="status",
            field=models.CharField(
                choices=[
                    ("PUBLISHED", "Published"),
                    ("DRAFT", "Draft"),
                    ("REPORTED", "Reported / Flagged"),
                    ("HIDDEN", "Hidden by Admin"),
                ],
                db_index=True,
                default="PUBLISHED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="studymaterial",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="studymaterial",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="materials/%Y/%m/"),
        ),
        migrations.AlterField(
            model_name="studymaterial",
            name="file_type",
            field=models.CharField(blank=True, default="PDF", max_length=50),
        ),
    ]
