# Generated by Django 5.2.11 on 2026-10-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0008_studymaterial_chapters_count_studymaterial_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchannouncement",
            name="admin_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="batchannouncement",
            name="code",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="batchannouncement",
            name="flag_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="batchannouncement",
            name="is_flagged",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="batchannouncement",
            name="priority",
            field=models.CharField(
                choices=[("NORMAL", "Normal"), ("HIGH", "High"), ("URGENT", "Urgent")],
                db_index=True,
                default="NORMAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="batchannouncement",
            name="status",
            field=models.CharField(
                choices=[
                    ("PUBLISHED", "Published"),
                    ("DRAFT", "Draft"),
                    ("FLAGGED", "Flagged"),
                ],
                db_index=True,
                default="PUBLISHED",
                max_length=20,
            ),
        ),
    ]
