# Generated by Django 5.1.15 on 2026-09-26 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classcontent",
            name="is_live",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="classcontent",
            name="joined_students_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="classcontent",
            name="status",
            field=models.CharField(
                choices=[
                    ("UPCOMING", "Upcoming"),
                    ("LIVE", "Live Now"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="UPCOMING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="studymaterial",
            name="access_type",
            field=models.CharField(
                choices=[("DOWNLOADABLE", "Downloadable"), ("PROTECTED", "Protected")],
                default="DOWNLOADABLE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="studymaterial",
            name="file_size_display",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name="StudentUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=150)),
                ("batch_title", models.CharField(blank=True, max_length=255)),
                (
                    "update_type",
                    models.CharField(
                        choices=[
                            ("JOINED_BATCH", "Joined batch"),
                            ("SENT_DOUBT", "Sent doubt query"),
                            ("ATTENDED_SESSION", "Attended session"),
                            ("SUBMITTED_ASSIGNMENT", "Submitted assignment"),
                            ("OTHER", "Other"),
                        ],
                        default="JOINED_BATCH",
                        max_length=30,
                    ),
                ),
                ("update_text", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_updates",
                        to="app.batch",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
