# Generated by Django 5.1.15 on 2026-09-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_classcontent_is_live_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="allow_installments",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="batch",
            name="class_days",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="batch",
            name="class_slot",
            field=models.CharField(
                blank=True, default="4:00 PM - 5:30 PM", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="cohort_perks",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="batch",
            name="delivery_format",
            field=models.CharField(
                choices=[
                    ("LIVE_INTERACTIVE", "Live Interactive Classes"),
                    ("PRERECORDED_DOUBTS", "Pre-recorded + Live Doubts"),
                    ("SELF_PACED", "Self-paced Complete Course"),
                ],
                default="LIVE_INTERACTIVE",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="discounted_price",
            field=models.DecimalField(decimal_places=2, default=4999.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="batch",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="batch",
            name="installment_amount",
            field=models.DecimalField(decimal_places=2, default=2600.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="batch",
            name="installment_months",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="batch",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="batch",
            name="is_paid",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="batch",
            name="is_unlimited_capacity",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="batch",
            name="language",
            field=models.CharField(default="Hinglish", max_length=50),
        ),
        migrations.AddField(
            model_name="batch",
            name="max_students_capacity",
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name="batch",
            name="original_price",
            field=models.DecimalField(decimal_places=2, default=7999.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="batch",
            name="target_exam",
            field=models.CharField(blank=True, default="JEE Advanced", max_length=100),
        ),
        migrations.AddField(
            model_name="batch",
            name="target_grade",
            field=models.CharField(
                blank=True, default="Class 12th & Droppers (Intensive)", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="batch",
            name="fee",
            field=models.DecimalField(decimal_places=2, default=4999.0, max_digits=10),
        ),
    ]
