# Generated by Django 5.1.15 on 2026-09-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_batch_allow_installments_batch_class_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="current_institution",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="exam_expertise",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="highest_qualification",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="id_proof_document",
            field=models.FileField(
                blank=True, null=True, upload_to="verifications/id/"
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="id_proof_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="qualification_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="verifications/certificates/"
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="qualification_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="specialization",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="university_institute",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
