# Generated by Django 5.1.15 on 2026-09-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_teacherprofile_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_type",
            new_name="role",
        ),
    ]
