# Generated by Django 5.1.15 on 2026-09-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_user_type_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="account_standing",
            field=models.CharField(default="GOOD_STANDING", max_length=50),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="emergency_contact",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="guardian_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="guardian_relationship",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="hours_learned",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="kyc_standing",
            field=models.CharField(default="VERIFIED", max_length=50),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="school_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="student_reference_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="total_logins",
            field=models.IntegerField(default=1),
        ),
    ]
